# Generated by Django 3.0.8 on 2020-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='data_modificacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
