# Generated by Django 3.0.8 on 2020-11-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_data_modificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
