version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8001"
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - redis
  celery:
    build: .
    command: bash -c "cd /code/ && celery -A front worker -l info"
    volumes:
      - .:/code
    depends_on:
      - redis
